# Original to the ghackett fork of agent-session-manager
# (https://github.com/r4nd3l/agent-session-manager, GPL-3.0): this file has no
# upstream version, so it carries no modification notice. Licensed GPL-3.0
# with the rest of the project.

"""Jobs: the service's long-running operations, reported as they go.

A request is answered once and at once; some of what a client asks of the
service takes seconds or minutes and has something to say meanwhile: a
clone (its progress, then a folder or the reason there is none), the
repository list the clone dialog picks from (a page at a time), a session
worktree moved to the trash or brought back, a chat folder made and trusted
before its session launches, a project icon generated by a headless run,
the CLI's login repaired by one (split-service spec §3.15, PR-1.11's
amendment). `job.start` names the kind and its arguments and is answered
with the job's id; the work runs on a daemon thread, and `job` events
report it to the client that started it: ``running`` (with progress as a
msgid and args, and sometimes a partial result), then exactly one of
``done`` (the result), ``failed`` (why, as a msgid and args), ``refused``
(arguments the kind does not take; rule 5) or ``cancelled`` (`job.cancel`,
which also ends whatever process the job runs: the clone's process group,
the icon's headless CLI).

The events are delivered on the main loop (*dispatch*, `GLib.idle_add` at
`PRIORITY_DEFAULT`: CI's Xvfb starves a default-idle landing), so a client
hears them where it draws, and the outcome always comes last. A client that
goes away is not the job's business: the work finishes and its events have
nobody to go to (§3.1 rule 5: a client going away changes nothing on the
service).

Strings a person sees cross as msgid and args (§3.14): the progress and
the failures are English source strings the client translates. Text the
job did not write itself, a git or gh error's words, crosses as the
argument of ``{error}``, as an agent's text does as its own msgid.

The workers (`WORKERS`) are the modules the dialogs used to call
themselves: `clonerepo` and `ghsetup` for the clone and its list,
`sessions.trash_worktree` / `restore_worktree`, `chats.create_chat_dir` /
`trust_chat_dir`, `icongen.IconRun`, `tokenrefresh.maybe_start` /
`maybe_repair`. They run on the service's machine, against its `gh`, its
git, its trash and its `~/.claude`. GLib only; nothing here imports GTK.
"""

from __future__ import annotations

import itertools
import logging
import os
import shutil
import signal
import subprocess
import threading
from collections.abc import Callable
from pathlib import Path
from typing import Any

from ..api import protocol

log = logging.getLogger(__name__)

Deliver = Callable[[dict], None]
Dispatch = Callable[[Callable[[], Any]], Any]


class JobRefused(Exception):
    """The job's arguments are not ones its kind takes."""

    def __init__(self, msgid: str, args: dict | None = None) -> None:
        super().__init__(msgid)
        self.msgid = msgid
        self.details = dict(args or {})


class JobFailed(Exception):
    """The job tried and it went wrong: why, as a msgid and args."""

    def __init__(self, msgid: str, args: dict | None = None) -> None:
        super().__init__(msgid)
        self.msgid = msgid
        self.details = dict(args or {})


class JobCancelled(Exception):
    """Raised by a worker that noticed its job was cancelled."""


def failure(text: object) -> JobFailed:
    """A failure in words the job did not write (git's, gh's, an OSError's):
    the argument of ``{error}``, bounded."""
    return JobFailed("{error}", {"error": str(text)[: protocol.ARG_TEXT_MAX]})


class Job:
    """One job in flight, as its worker sees it."""

    def __init__(self, runner: JobRunner, job_id: str, kind: str, deliver: Deliver) -> None:
        self._runner = runner
        self.id = job_id
        self.kind = kind
        self._deliver = deliver
        self._cancelled = threading.Event()
        self._lock = threading.Lock()
        self._on_cancel: list[Callable[[], None]] = []
        self.finished = False

    @property
    def cancelled(self) -> bool:
        return self._cancelled.is_set()

    def on_cancel(self, callback: Callable[[], None]) -> None:
        """Run *callback* if the job is cancelled (now, when it already
        was): what ends the process the job runs."""
        with self._lock:
            if not self._cancelled.is_set():
                self._on_cancel.append(callback)
                return
        _quietly(callback)

    def cancel(self) -> None:
        with self._lock:
            if self._cancelled.is_set():
                return
            self._cancelled.set()
            callbacks, self._on_cancel = self._on_cancel, []
        for callback in callbacks:
            _quietly(callback)

    def check(self) -> None:
        """Raise JobCancelled when the job was cancelled: a worker's
        checkpoint between steps."""
        if self.cancelled:
            raise JobCancelled()

    def progress(self, msgid: str = "", args: dict | None = None, result: dict | None = None) -> None:
        """A ``running`` event: what the job is doing, and what it has so
        far. Safe from the worker's thread."""
        self._runner._emit(self, protocol.JOB_RUNNING, msgid, args, result)


def _quietly(callback: Callable[[], None]) -> None:
    try:
        callback()
    except Exception:
        log.exception("jobs: a cancel callback failed")


def _thread(target: Callable[[], None], name: str) -> None:
    threading.Thread(target=target, name=name, daemon=True).start()


def _main_loop(fn: Callable[[], Any]) -> None:
    from gi.repository import GLib

    def run() -> bool:
        fn()
        return GLib.SOURCE_REMOVE

    GLib.idle_add(run, priority=GLib.PRIORITY_DEFAULT)


class JobRunner:
    """The job table: starts jobs, cancels them, and reports them. See the
    module docstring. *workers* maps a kind to ``worker(job, args) ->
    result``; *dispatch* puts a callable on the main loop (inline in a
    test); *spawn* runs the work (a daemon thread; inline in a test)."""

    def __init__(
        self,
        workers: dict[str, Callable[[Job, dict], dict | None]] | None = None,
        dispatch: Dispatch | None = None,
        spawn: Callable[[Callable[[], None], str], None] | None = None,
    ) -> None:
        self._workers = dict(WORKERS if workers is None else workers)
        self._dispatch = dispatch or _main_loop
        self._spawn = spawn or _thread
        self._ids = itertools.count(1)
        self.jobs: dict[str, Job] = {}

    def start(self, kind: str, args: dict, deliver: Deliver) -> str:
        """Start a job of *kind* and return its id; its events go to
        *deliver*. A kind with no worker is refused as a job (its outcome
        the first and last event), never by raising."""
        job = Job(self, f"job-{next(self._ids)}", kind, deliver)
        self.jobs[job.id] = job
        worker = self._workers.get(kind)

        def work() -> None:
            try:
                if worker is None:
                    raise JobRefused("No such job: {kind}", {"kind": kind})
                result = worker(job, dict(args or {}))
            except JobCancelled:
                self._finish(job, protocol.JOB_CANCELLED)
            except JobRefused as refused:
                self._finish(job, protocol.JOB_REFUSED, refused.msgid, refused.details)
            except JobFailed as failed:
                if job.cancelled:
                    self._finish(job, protocol.JOB_CANCELLED)
                else:
                    self._finish(job, protocol.JOB_FAILED, failed.msgid, failed.details)
            except Exception as error:  # never leave a client waiting on a job
                log.exception("jobs: a %s job failed", kind)
                self._finish(job, protocol.JOB_FAILED, "{error}", {"error": str(error)[:200]})
            else:
                if job.cancelled:
                    self._finish(job, protocol.JOB_CANCELLED)
                else:
                    self._finish(job, protocol.JOB_DONE, result=result or {})

        self._spawn(work, f"job-{kind}")
        return job.id

    def cancel(self, job_id: str) -> bool:
        """Cancel a job still running; False for one that is not."""
        job = self.jobs.get(job_id)
        if job is None or job.finished:
            return False
        job.cancel()
        return True

    def forget(self, deliver: Deliver) -> None:
        """A client went away: its jobs finish with nobody to tell."""
        for job in list(self.jobs.values()):
            # == rather than is: a bound method is a new object per access.
            if job._deliver is not None and job._deliver == deliver:
                job._deliver = None

    def _finish(self, job: Job, state: str, msgid: str = "", args=None, result=None) -> None:
        def landed() -> None:
            job.finished = True
            self.jobs.pop(job.id, None)

        self._emit(job, state, msgid, args, result, then=landed)

    def _emit(self, job: Job, state: str, msgid: str, args, result, then=None) -> None:
        event = protocol.event("job", job=job.id, kind=job.kind, state=state)
        if msgid:
            event["msgid"] = msgid[: protocol.MSGID_MAX]
        if args:
            event["args"] = _bounded_args(args)
        if result is not None:
            event["result"] = result

        def deliver() -> None:
            if then is not None:
                then()
            target = job._deliver
            if target is None:
                return
            try:
                target(event)
            except Exception:
                log.exception("jobs: a client's delivery failed")

        self._dispatch(deliver)


def _bounded_args(args: dict) -> dict:
    out: dict = {}
    for key, value in list(args.items())[: protocol.ARGS_MAX]:
        if isinstance(value, str):
            value = value[: protocol.ARG_TEXT_MAX]
        elif not (value is None or isinstance(value, (bool, int, float))):
            value = str(value)[: protocol.ARG_TEXT_MAX]
        out[str(key)] = value
    return out


# ---- the workers --------------------------------------------------------------


def _text(args: dict, name: str, limit: int = protocol.PATH_MAX) -> str:
    value = args.get(name)
    if not isinstance(value, str) or not value or len(value) > limit or "\0" in value:
        raise JobRefused("{field} is missing or not text", {"field": name})
    return value


def _path(args: dict, name: str) -> str:
    value = _text(args, name)
    if not value.startswith("/"):
        raise JobRefused("{field} must be an absolute path", {"field": name})
    return value


def clone(job: Job, args: dict) -> dict:
    """Clone a repository into a new folder: `gh repo clone` for GitHub,
    `git clone` otherwise (clonerepo.clone_argv), in its own process group
    so a cancel ends gh and the git under it, and git's own signal handler
    removes the folder it had started."""
    from .. import clonerepo

    source = args.get("source")
    if not isinstance(source, dict):
        raise JobRefused("{field} is missing or not text", {"field": "source"})
    kind = source.get("kind")
    spec = source.get("spec")
    name = source.get("name")
    if kind not in (clonerepo.GITHUB, clonerepo.GIT) or not all(
        isinstance(v, str) and v and len(v) <= protocol.PATH_MAX for v in (spec, name)
    ):
        raise JobRefused("Not a repository to clone")
    parsed = clonerepo.parse_source(spec)
    if parsed is None or parsed.kind != kind:
        raise JobRefused("Not a repository to clone")
    dest = Path(_path(args, "dest"))
    argv = clonerepo.clone_argv(parsed, dest, shutil.which("gh"), shutil.which("git") or "git")
    log.info("clone: %s", " ".join(argv))
    job.check()
    try:
        proc = subprocess.Popen(
            argv,
            stdin=subprocess.DEVNULL,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            env=clonerepo.clone_env(dict(os.environ)),
            start_new_session=True,  # no terminal to prompt on; killable as a group
            text=True,
            errors="replace",
        )
    except OSError as error:
        raise failure(error) from None

    def kill() -> None:
        if proc.poll() is None:
            try:
                os.killpg(proc.pid, signal.SIGTERM)
            except OSError:
                pass

    job.on_cancel(kill)
    job.progress("Cloning…")
    output, _unused = proc.communicate()
    job.check()
    if proc.returncode == 0 and dest.is_dir():
        return {"path": str(dest)}
    summary = clonerepo.error_summary(output or "")
    if summary:
        raise failure(summary)
    raise JobFailed("The clone failed (exit status {code})", {"code": proc.returncode})


def clone_repos(job: Job, args: dict) -> dict:
    """The repositories the signed-in user can see, a page at a time (each
    page a ``running`` event whose result is the list so far), through the
    service's gh. A gh that is missing or signed out is the result's
    ``problem`` (ghsetup's word), not a failure: the dialog says what it
    is holding back."""
    from .. import clonerepo, ghsetup
    from ..prstatus import gh_json

    state = ghsetup.check()
    if state != ghsetup.READY:
        return {"repos": None, "problem": state}

    def page(fetch_args: list[str]):
        job.check()
        return gh_json(fetch_args, timeout=clonerepo.PAGE_TIMEOUT_S)

    repos = clonerepo.fetch_repos(
        page, lambda so_far: job.progress(result={"repos": clonerepo.repo_records(so_far)})
    )
    if repos is None:
        return {"repos": None, "problem": "failed"}
    return {"repos": clonerepo.repo_records(repos), "problem": None}


def _worktree_state(args: dict) -> dict:
    state = args.get("state")
    if not isinstance(state, dict):
        raise JobRefused("{field} is missing or not text", {"field": "state"})
    path = state.get("worktreePath")
    if not isinstance(path, str) or not path.startswith("/") or "\0" in path:
        raise JobRefused("{field} must be an absolute path", {"field": "worktreePath"})
    return state


def worktree_trash(job: Job, args: dict) -> dict:
    """A stopped session's worktree, moved to the service machine's trash
    (sessions.trash_worktree)."""
    from ..sessions import trash_worktree

    error = trash_worktree(_worktree_state(args))
    if error:
        raise failure(error)
    return {}


def worktree_restore(job: Job, args: dict) -> dict:
    """The trashed worktree, put back (sessions.restore_worktree)."""
    from ..sessions import restore_worktree

    error = restore_worktree(_worktree_state(args))
    if error:
        raise failure(error)
    return {}


def chats_trust(job: Job, args: dict) -> dict:
    """A chat's throwaway folder, made (``create``) and pre-trusted in the
    CLI's config (chats.trust_chat_dir: only a folder under the chats root
    is ever trusted this way)."""
    from .. import chats

    if args.get("create") is True:
        try:
            cwd = chats.create_chat_dir()
        except OSError as error:
            raise failure(error) from None
    else:
        cwd = _path(args, "cwd")
        # One that was swept or trashed since is made again (what the
        # window's chats.ensure_chat_dir did before PR-1.12d): a no-op for a
        # folder outside the chats root.
        chats.ensure_chat_dir(cwd)
    chats.trust_chat_dir(cwd)
    return {"cwd": cwd}


def icon(job: Job, args: dict) -> dict:
    """A project icon, generated by a headless run (icongen.IconRun, which
    goes through titles.headless_argv from the scratch dir: rule 6). The
    result is the SVG's text; saving it is `icon.save`'s."""
    from .. import icongen

    cwd = _path(args, "cwd")
    project = _text(args, "project", protocol.NAME_MAX)
    feedback = args.get("feedback") if isinstance(args.get("feedback"), str) else ""
    previous = args.get("previous")
    previous = previous.encode("utf-8") if isinstance(previous, str) and previous else None
    model = args.get("model") if isinstance(args.get("model"), str) and args.get("model") else None
    run = icongen.IconRun()
    job.on_cancel(run.cancel)
    try:
        prompt = icongen.build_prompt(cwd, project, feedback=feedback, previous_svg=previous)
        svg = run.run(prompt, model=model)
    except icongen.IconGenCancelled:
        raise JobCancelled() from None
    except Exception as error:  # IconGenError, OSError, ...
        raise failure(error) from None
    return {"svg": svg.decode("utf-8", errors="replace")}


def login_repair(job: Job, args: dict) -> dict:
    """The CLI's login, repaired by a throwaway headless run when it is
    dead (tokenrefresh): ``mode`` ``start`` checks the token first (the
    launch's), ``repair`` trusts the caller's word that a fetch was just
    refused for it (the usage panel's). The result says whether a refresh
    happened; nothing at all ran when a repair was cooling down."""
    from .. import tokenrefresh

    mode = args.get("mode")
    if mode not in ("start", "repair"):
        raise JobRefused("{field} must be one of: {choices}", {"field": "mode", "choices": "repair, start"})
    refreshed = threading.Event()
    # A cancel stops the wait, not the run: tokenrefresh's own thread is
    # single-flight and cooled down, and finishes its repair (or not) by
    # itself; the job just stops listening for it.
    stop = threading.Event()
    job.on_cancel(stop.set)
    entry = tokenrefresh.maybe_start if mode == "start" else tokenrefresh.maybe_repair
    thread = entry(refreshed.set)
    if thread is not None:
        while thread.is_alive():
            if stop.wait(_REPAIR_POLL_S):
                raise JobCancelled()
    return {"refreshed": refreshed.is_set(), "ran": thread is not None}


# How often a login repair's wait looks up from its thread to see whether
# the job was cancelled.
_REPAIR_POLL_S = 0.1


WORKERS: dict[str, Callable[[Job, dict], dict | None]] = {
    "clone": clone,
    "clone.repos": clone_repos,
    "worktree.trash": worktree_trash,
    "worktree.restore": worktree_restore,
    "chats.trust": chats_trust,
    "icon": icon,
    "login.repair": login_repair,
}
