#!/usr/bin/env python3
"""Generate per-language .po files and compile .mo into the package.

Run from the repo root:  python3 po/generate.py
Re-run after `xgettext` updates po/claude-session-manager.pot with new strings;
fill any new msgids in TRANSLATIONS below (missing ones fall back to English).
"""

from __future__ import annotations

import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LOCALE = ROOT / "claude_session_manager" / "locale"
DOMAIN = "claude-session-manager"

TRANSLATIONS: dict[str, dict[str, str]] = {
    "hu": {
        "Rename session": "Munkamenet átnevezése",
        "Custom name": "Egyéni név",
        "Cancel": "Mégse",
        "Session list": "Munkamenet-lista",
        "Show folder path": "Mappa elérési útjának megjelenítése",
        "Show each session's project folder path in the sidebar":
            "Az egyes munkamenetek projektmappájának elérési útja az oldalsávon",
        "Open session file…": "Munkamenetfájl megnyitása…",
        "Open session transcript": "Munkamenet-átirat megnyitása",
        "Session transcripts (*.jsonl)": "Munkamenet-átiratok (*.jsonl)",
        "Could not open transcript": "Az átirat nem nyitható meg",
        "The file couldn't be read as a session transcript.":
            "A fájl nem olvasható be munkamenet-átiratként.",
        "Delete permanently…": "Végleges törlés…",
        "Could not delete transcript": "Az átirat nem törölhető",
        "Delete session permanently?": "Véglegesen törlöd a munkamenetet?",
        "“{name}” and its transcript file will be permanently deleted. This cannot be undone.":
            "A(z) „{name}” és az átiratfájlja véglegesen törlődik. Ez nem vonható vissza.",
        "Delete permanently": "Végleges törlés",
        "New {name} session (advanced)…": "Új {name} munkamenet (haladó)…",
        "Continue last {name} session…": "Utolsó {name} munkamenet folytatása…",
        "New {name} session": "Új {name} munkamenet",
        "Optional flags for this session.": "Választható kapcsolók ehhez a munkamenethez.",
        "Model": "Modell",
        "Default": "Alapértelmezett",
        "Permission mode": "Engedélyezési mód",
        "Extra directory": "További könyvtár",
        "Choose…": "Választás…",
        "Choose a directory": "Válassz egy könyvtárat",
        "Start": "Indítás",
        "Save": "Mentés",
        "Set tab emoji": "Lap emodzsi beállítása",
        "Shown before the tab title. Leave empty to remove.":
            "A lap címe előtt jelenik meg. Hagyd üresen az eltávolításhoz.",
        "e.g. 🚀": "pl. 🚀",
        "OK": "OK",
        "No MCP servers configured": "Nincs konfigurált MCP-kiszolgáló",
        "Global": "Globális",
        "Available to every project": "Minden projekthez elérhető",
        "MCP Servers": "MCP-kiszolgálók",
        "Read-only": "Csak olvasható",
        "Reading transcript…": "Átirat olvasása…",
        "Session details": "Munkamenet részletei",
        "Session ID": "Munkamenet-azonosító",
        "Directory": "Könyvtár",
        "unknown": "ismeretlen",
        "Created": "Létrehozva",
        "Last activity": "Utolsó tevékenység",
        "Messages": "Üzenetek",
        "Tool calls": "Eszközhívások",
        "Models": "Modellek",
        "Tokens": "Tokenek",
        "Transcript size": "Átirat mérete",
        "MCP": "MCP",
        "Available to this project": "Ehhez a projekthez elérhető",
        "Tools used in this session": "A munkamenetben használt eszközök",
        "Recent activity": "Legutóbbi tevékenység",
        "You": "Te",
        "Claude": "Claude",
        "Follow system": "Rendszer követése",
        "Light": "Világos",
        "Dark": "Sötét",
        "Preferences": "Beállítások",
        "General": "Általános",
        "Terminal": "Terminál",
        "Font": "Betűtípus",
        "Applies to all terminal tabs": "Minden terminállapra érvényes",
        "Reset to default font": "Visszaállítás az alapértelmezett betűtípusra",
        "Scrollback lines": "Visszagörgetési sorok",
        "Easy copy & paste": "Egyszerű másolás és beillesztés",
        "Ctrl+C copies selected text (otherwise interrupts as usual), Ctrl+V pastes, and right-click opens a copy/paste menu":
            "A Ctrl+C másolja a kijelölt szöveget (különben szokás szerint megszakít), a Ctrl+V beilleszt, a jobb kattintás pedig másolás/beillesztés menüt nyit",
        "Copy": "Másolás",
        "Paste": "Beillesztés",
        "Select All": "Összes kijelölése",
        "Color theme": "Színtéma",
        "Appearance": "Megjelenés",
        "Color scheme": "Színséma",
        "Language": "Nyelv",
        "Restart to apply": "Újraindítás szükséges",
        "Notifications": "Értesítések",
        "Notify when a session goes idle": "Értesítés, ha egy munkamenet tétlenné válik",
        "Desktop notification when a background tab stops producing output":
            "Asztali értesítés, amikor egy háttérlap abbahagyja a kimenet előállítását",
        "Claude is waiting for your reply": "A Claude a válaszodra vár",
        "Remove from favorites": "Eltávolítás a kedvencekből",
        "Add to favorites": "Hozzáadás a kedvencekhez",
        "Sessions": "Munkamenetek",
        "Select sessions": "Munkamenetek kijelölése",
        "Show hidden sessions": "Rejtett munkamenetek megjelenítése",
        "MCP servers": "MCP-kiszolgálók",
        "About Agent Session Manager": "Az Agent Session Manager névjegye",
        "Refresh session list": "Munkamenetlista frissítése",
        "Search sessions…": "Munkamenetek keresése…",
        "Collapse all groups": "Összes csoport összecsukása",
        "Expand all groups": "Összes csoport kibontása",
        "No sessions found": "Nincs találat",
        "{n} sessions": "{n} munkamenet",
        "{n} projects": "{n} projekt",
        "{n} open": "{n} megnyitva",
        "Favorites": "Kedvencek",
        "Open": "Megnyitás",
        "Open in Ghostty": "Megnyitás Ghosttyban",
        "Fork session": "Munkamenet elágaztatása",
        "Rename…": "Átnevezés…",
        "Details…": "Részletek…",
        "Copy session ID": "Munkamenet-azonosító másolása",
        "Export as Markdown…": "Exportálás Markdownként…",
        "Reveal transcript": "Átirat megjelenítése",
        "Unhide session": "Munkamenet felfedése",
        "Hide session": "Munkamenet elrejtése",
        "Move transcript to trash…": "Átirat kukába helyezése…",
        "All": "Mind",
        "Select all (filtered) sessions": "Az összes (szűrt) munkamenet kijelölése",
        "None": "Egyik sem",
        "Clear selection": "Kijelölés törlése",
        "Move selected transcripts to trash…": "Kijelölt átiratok kukába helyezése…",
        "Hide selected": "Kijelöltek elrejtése",
        "Remove selected from favorites": "Kijelöltek eltávolítása a kedvencekből",
        "Add selected to favorites": "Kijelöltek hozzáadása a kedvencekhez",
        "Open selected in tabs": "Kijelöltek megnyitása lapokon",
        "warning: project dir {cwd} no longer exists, starting in HOME":
            "figyelmeztetés: a(z) {cwd} projektkönyvtár már nem létezik, indítás a HOME-ban",
        "warning: `{cli}` not found in PATH — starting a plain shell":
            "figyelmeztetés: a `{cli}` nem található a PATH-ban — egyszerű parancsértelmező indítása",
        "failed to start shell: {msg}": "nem sikerült elindítani a parancsértelmezőt: {msg}",
        "Find in terminal…": "Keresés a terminálban…",
        "Previous match": "Előző találat",
        "Next match": "Következő találat",
        "Set emoji…": "Emodzsi beállítása…",
        "Close": "Bezárás",
        "Toggle sidebar (F9)": "Oldalsáv ki/be (F9)",
        "New {name} session…": "Új {name} munkamenet…",
        "New session (Ctrl+Shift+T)": "Új munkamenet (Ctrl+Shift+T)",
        "Agent": "Ügynök",
        "Question": "Kérdés",
        "{n} questions": "{n} kérdés",
        "This prompt needs the terminal to answer.":
            "Ezt a kérdést a terminálban kell megválaszolni.",
        "Answer in terminal": "Válasz a terminálban",
        "New {name} chat…": "Új {name} csevegés…",
        "Chat with {name} — every file edit and command asks your permission first.":
            "Csevegés a {name}-tal — minden fájlmódosítás és parancs előbb az engedélyedet kéri.",
        "New {name} chat ({mode})": "Új {name} csevegés ({mode})",
        "ask, read-only": "kérdés, csak olvasható",
        "trusted, auto-run": "megbízható, automatikus",
        "Read-only chat with {name} — analyses and answers, never edits.":
            "Csak olvasható csevegés a {name}-tal — elemez és válaszol, soha nem szerkeszt.",
        "Chat with {name} — ⚠ runs edits and commands automatically, without asking.":
            "Csevegés a {name}-tal — ⚠ a módosításokat és parancsokat automatikusan, kérdés nélkül futtatja.",
        "{name} wants to use {tool}": "A {name} a(z) {tool} eszközt szeretné használni",
        "Allow once": "Egyszeri engedélyezés",
        "Always allow {tool}": "{tool} mindig engedélyezve",
        "Deny": "Elutasítás",
        "Allowed {tool}.": "{tool} engedélyezve.",
        "Always allowing {tool}.": "{tool} mostantól mindig engedélyezve.",
        "Denied {tool}.": "{tool} elutasítva.",
        "Auto-allowed {tool}": "{tool} automatikusan engedélyezve",
        "Ask {name}…": "Kérdezd a {name}-t…",
        "Stop": "Leállítás",
        "{name} is thinking…": "A {name} gondolkodik…",
        "Rate limited — try again later.": "Korlátozva — próbáld újra később.",
        "Error: {msg}": "Hiba: {msg}",
        "Session ended.": "A munkamenet véget ért.",
        "Replay…": "Visszajátszás…",
        "Replay — {name}": "Visszajátszás — {name}",
        "Previous": "Előző",
        "Play": "Lejátszás",
        "Next": "Következő",
        "Show all": "Összes megjelenítése",
        "Nothing to replay yet.": "Még nincs mit visszajátszani.",
        "Chat — {dir}": "Csevegés — {dir}",
        "Chat — {name}": "Csevegés — {name}",
        "Continue in chat": "Folytatás csevegésben",
        "Continue in chat ({mode})": "Folytatás csevegésben ({mode})",
        "Continuing the previous session — earlier messages aren't shown here.":
            "A korábbi munkamenet folytatása — a régebbi üzenetek itt nem jelennek meg.",
        "Close all tabs": "Összes lap bezárása",
        "No session open": "Nincs megnyitott munkamenet",
        "Pick a session from the sidebar, or start a new one.":
            "Válassz egy munkamenetet az oldalsávból, vagy indíts egy újat.",
        "Some transcripts could not be trashed": "Néhány átiratot nem sikerült a kukába helyezni",
        "Move {n} transcript(s) to trash?": "{n} átirat kukába helyezése?",
        "The files are moved to the trash and can be restored.":
            "A fájlok a kukába kerülnek, és visszaállíthatók.",
        "Move to Trash": "Kukába",
        "New window": "Új ablak",
        "You interrupted Claude here": "Itt szakítottad meg a Claude-ot",
        "Restart now": "Újraindítás most",
        "Choose project directory": "Válassz projektkönyvtárat",
        "Tab name": "Lap neve",
        "Export session as Markdown": "Munkamenet exportálása Markdownként",
        "Export failed": "Az exportálás sikertelen",
        "Could not trash transcript": "Az átiratot nem sikerült a kukába helyezni",
        "Move transcript to trash?": "Átirat kukába helyezése?",
        "“{name}” will be removed from Claude's history.":
            "A(z) „{name}” eltávolításra kerül a Claude előzményeiből.",
        "The file is moved to the trash and can be restored.":
            "A fájl a kukába kerül, és visszaállítható.",
    },
    "de": {
        "Rename session": "Sitzung umbenennen",
        "Custom name": "Eigener Name",
        "Cancel": "Abbrechen",
        "Session list": "Sitzungsliste",
        "Show folder path": "Ordnerpfad anzeigen",
        "Show each session's project folder path in the sidebar":
            "Den Projektordnerpfad jeder Sitzung in der Seitenleiste anzeigen",
        "Open session file…": "Sitzungsdatei öffnen…",
        "Open session transcript": "Sitzungsprotokoll öffnen",
        "Session transcripts (*.jsonl)": "Sitzungsprotokolle (*.jsonl)",
        "Could not open transcript": "Protokoll konnte nicht geöffnet werden",
        "The file couldn't be read as a session transcript.":
            "Die Datei konnte nicht als Sitzungsprotokoll gelesen werden.",
        "Delete permanently…": "Endgültig löschen…",
        "Could not delete transcript": "Protokoll konnte nicht gelöscht werden",
        "Delete session permanently?": "Sitzung endgültig löschen?",
        "“{name}” and its transcript file will be permanently deleted. This cannot be undone.":
            "„{name}“ und die zugehörige Protokolldatei werden endgültig gelöscht. "
            "Dies kann nicht rückgängig gemacht werden.",
        "Delete permanently": "Endgültig löschen",
        "New {name} session (advanced)…": "Neue {name}-Sitzung (erweitert)…",
        "Continue last {name} session…": "Letzte {name}-Sitzung fortsetzen…",
        "New {name} session": "Neue {name}-Sitzung",
        "Optional flags for this session.": "Optionale Flags für diese Sitzung.",
        "Model": "Modell",
        "Default": "Standard",
        "Permission mode": "Berechtigungsmodus",
        "Extra directory": "Zusätzliches Verzeichnis",
        "Choose…": "Auswählen…",
        "Choose a directory": "Verzeichnis auswählen",
        "Start": "Starten",
        "Save": "Speichern",
        "Set tab emoji": "Tab-Emoji festlegen",
        "Shown before the tab title. Leave empty to remove.":
            "Wird vor dem Tab-Titel angezeigt. Zum Entfernen leer lassen.",
        "e.g. 🚀": "z. B. 🚀",
        "OK": "OK",
        "No MCP servers configured": "Keine MCP-Server konfiguriert",
        "Global": "Global",
        "Available to every project": "Für jedes Projekt verfügbar",
        "MCP Servers": "MCP-Server",
        "Read-only": "Schreibgeschützt",
        "Reading transcript…": "Transkript wird gelesen…",
        "Session details": "Sitzungsdetails",
        "Session ID": "Sitzungs-ID",
        "Directory": "Verzeichnis",
        "unknown": "unbekannt",
        "Created": "Erstellt",
        "Last activity": "Letzte Aktivität",
        "Messages": "Nachrichten",
        "Tool calls": "Tool-Aufrufe",
        "Models": "Modelle",
        "Tokens": "Tokens",
        "Transcript size": "Transkriptgröße",
        "MCP": "MCP",
        "Available to this project": "Für dieses Projekt verfügbar",
        "Tools used in this session": "In dieser Sitzung verwendete Tools",
        "Recent activity": "Letzte Aktivität",
        "You": "Du",
        "Claude": "Claude",
        "Follow system": "System folgen",
        "Light": "Hell",
        "Dark": "Dunkel",
        "Preferences": "Einstellungen",
        "General": "Allgemein",
        "Terminal": "Terminal",
        "Font": "Schriftart",
        "Applies to all terminal tabs": "Gilt für alle Terminal-Tabs",
        "Reset to default font": "Auf Standardschriftart zurücksetzen",
        "Scrollback lines": "Scrollback-Zeilen",
        "Easy copy & paste": "Einfaches Kopieren & Einfügen",
        "Ctrl+C copies selected text (otherwise interrupts as usual), Ctrl+V pastes, and right-click opens a copy/paste menu":
            "Strg+C kopiert markierten Text (unterbricht sonst wie üblich), Strg+V fügt ein, und Rechtsklick öffnet ein Kopieren/Einfügen-Menü",
        "Copy": "Kopieren",
        "Paste": "Einfügen",
        "Select All": "Alles auswählen",
        "Color theme": "Farbthema",
        "Appearance": "Erscheinungsbild",
        "Color scheme": "Farbschema",
        "Language": "Sprache",
        "Restart to apply": "Neustart erforderlich",
        "Notifications": "Benachrichtigungen",
        "Notify when a session goes idle": "Benachrichtigen, wenn eine Sitzung untätig wird",
        "Desktop notification when a background tab stops producing output":
            "Desktop-Benachrichtigung, wenn ein Hintergrund-Tab keine Ausgabe mehr erzeugt",
        "Claude is waiting for your reply": "Claude wartet auf deine Antwort",
        "Remove from favorites": "Aus Favoriten entfernen",
        "Add to favorites": "Zu Favoriten hinzufügen",
        "Sessions": "Sitzungen",
        "Select sessions": "Sitzungen auswählen",
        "Show hidden sessions": "Versteckte Sitzungen anzeigen",
        "MCP servers": "MCP-Server",
        "About Agent Session Manager": "Über Agent Session Manager",
        "Refresh session list": "Sitzungsliste aktualisieren",
        "Search sessions…": "Sitzungen suchen…",
        "Collapse all groups": "Alle Gruppen einklappen",
        "Expand all groups": "Alle Gruppen ausklappen",
        "No sessions found": "Keine Sitzungen gefunden",
        "{n} sessions": "{n} Sitzungen",
        "{n} projects": "{n} Projekte",
        "{n} open": "{n} geöffnet",
        "Favorites": "Favoriten",
        "Open": "Öffnen",
        "Open in Ghostty": "In Ghostty öffnen",
        "Fork session": "Sitzung verzweigen",
        "Rename…": "Umbenennen…",
        "Details…": "Details…",
        "Copy session ID": "Sitzungs-ID kopieren",
        "Export as Markdown…": "Als Markdown exportieren…",
        "Reveal transcript": "Transkript anzeigen",
        "Unhide session": "Sitzung einblenden",
        "Hide session": "Sitzung ausblenden",
        "Move transcript to trash…": "Transkript in den Papierkorb verschieben…",
        "All": "Alle",
        "Select all (filtered) sessions": "Alle (gefilterten) Sitzungen auswählen",
        "None": "Keine",
        "Clear selection": "Auswahl aufheben",
        "Move selected transcripts to trash…":
            "Ausgewählte Transkripte in den Papierkorb verschieben…",
        "Hide selected": "Ausgewählte ausblenden",
        "Remove selected from favorites": "Ausgewählte aus Favoriten entfernen",
        "Add selected to favorites": "Ausgewählte zu Favoriten hinzufügen",
        "Open selected in tabs": "Ausgewählte in Tabs öffnen",
        "warning: project dir {cwd} no longer exists, starting in HOME":
            "Warnung: Projektverzeichnis {cwd} existiert nicht mehr, starte im HOME",
        "warning: `{cli}` not found in PATH — starting a plain shell":
            "Warnung: `{cli}` nicht im PATH gefunden — starte eine einfache Shell",
        "failed to start shell: {msg}": "Shell konnte nicht gestartet werden: {msg}",
        "Find in terminal…": "Im Terminal suchen…",
        "Previous match": "Vorheriger Treffer",
        "Next match": "Nächster Treffer",
        "Set emoji…": "Emoji festlegen…",
        "Close": "Schließen",
        "Toggle sidebar (F9)": "Seitenleiste umschalten (F9)",
        "New {name} session…": "Neue {name}-Sitzung…",
        "New session (Ctrl+Shift+T)": "Neue Sitzung (Strg+Umschalt+T)",
        "Agent": "Agent",
        "Question": "Frage",
        "{n} questions": "{n} Fragen",
        "This prompt needs the terminal to answer.":
            "Diese Eingabe muss im Terminal beantwortet werden.",
        "Answer in terminal": "Im Terminal antworten",
        "New {name} chat…": "Neuer {name}-Chat…",
        "Chat with {name} — every file edit and command asks your permission first.":
            "Chat mit {name} — jede Dateiänderung und jeder Befehl fragt zuerst um Erlaubnis.",
        "New {name} chat ({mode})": "Neuer {name}-Chat ({mode})",
        "ask, read-only": "fragen, schreibgeschützt",
        "trusted, auto-run": "vertraut, automatisch",
        "Read-only chat with {name} — analyses and answers, never edits.":
            "Schreibgeschützter Chat mit {name} — analysiert und antwortet, bearbeitet nie.",
        "Chat with {name} — ⚠ runs edits and commands automatically, without asking.":
            "Chat mit {name} — ⚠ führt Änderungen und Befehle automatisch ohne Nachfrage aus.",
        "{name} wants to use {tool}": "{name} möchte {tool} verwenden",
        "Allow once": "Einmal erlauben",
        "Always allow {tool}": "{tool} immer erlauben",
        "Deny": "Ablehnen",
        "Allowed {tool}.": "{tool} erlaubt.",
        "Always allowing {tool}.": "{tool} wird ab jetzt immer erlaubt.",
        "Denied {tool}.": "{tool} abgelehnt.",
        "Auto-allowed {tool}": "{tool} automatisch erlaubt",
        "Ask {name}…": "{name} fragen…",
        "Stop": "Stopp",
        "{name} is thinking…": "{name} denkt nach…",
        "Rate limited — try again later.": "Ratenlimit erreicht — später erneut versuchen.",
        "Error: {msg}": "Fehler: {msg}",
        "Session ended.": "Sitzung beendet.",
        "Replay…": "Wiedergabe…",
        "Replay — {name}": "Wiedergabe — {name}",
        "Previous": "Zurück",
        "Play": "Abspielen",
        "Next": "Weiter",
        "Show all": "Alle anzeigen",
        "Nothing to replay yet.": "Noch nichts abzuspielen.",
        "Chat — {dir}": "Chat — {dir}",
        "Chat — {name}": "Chat — {name}",
        "Continue in chat": "Im Chat fortsetzen",
        "Continue in chat ({mode})": "Im Chat fortsetzen ({mode})",
        "Continuing the previous session — earlier messages aren't shown here.":
            "Frühere Sitzung wird fortgesetzt — ältere Nachrichten werden hier nicht angezeigt.",
        "Close all tabs": "Alle Tabs schließen",
        "No session open": "Keine Sitzung geöffnet",
        "Pick a session from the sidebar, or start a new one.":
            "Wähle eine Sitzung in der Seitenleiste oder starte eine neue.",
        "Some transcripts could not be trashed":
            "Einige Transkripte konnten nicht in den Papierkorb verschoben werden",
        "Move {n} transcript(s) to trash?": "{n} Transkript(e) in den Papierkorb verschieben?",
        "The files are moved to the trash and can be restored.":
            "Die Dateien werden in den Papierkorb verschoben und können wiederhergestellt werden.",
        "Move to Trash": "In den Papierkorb",
        "New window": "Neues Fenster",
        "You interrupted Claude here": "Du hast Claude hier unterbrochen",
        "Restart now": "Jetzt neu starten",
        "Choose project directory": "Projektverzeichnis wählen",
        "Tab name": "Tab-Name",
        "Export session as Markdown": "Sitzung als Markdown exportieren",
        "Export failed": "Export fehlgeschlagen",
        "Could not trash transcript":
            "Transkript konnte nicht in den Papierkorb verschoben werden",
        "Move transcript to trash?": "Transkript in den Papierkorb verschieben?",
        "“{name}” will be removed from Claude's history.":
            "„{name}“ wird aus Claudes Verlauf entfernt.",
        "The file is moved to the trash and can be restored.":
            "Die Datei wird in den Papierkorb verschoben und kann wiederhergestellt werden.",
    },
    "es": {
        "Rename session": "Renombrar sesión",
        "Custom name": "Nombre personalizado",
        "Cancel": "Cancelar",
        "Session list": "Lista de sesiones",
        "Show folder path": "Mostrar ruta de carpeta",
        "Show each session's project folder path in the sidebar":
            "Mostrar la ruta de la carpeta del proyecto de cada sesión en la barra lateral",
        "Open session file…": "Abrir archivo de sesión…",
        "Open session transcript": "Abrir transcripción de sesión",
        "Session transcripts (*.jsonl)": "Transcripciones de sesión (*.jsonl)",
        "Could not open transcript": "No se pudo abrir la transcripción",
        "The file couldn't be read as a session transcript.":
            "No se pudo leer el archivo como transcripción de sesión.",
        "Delete permanently…": "Eliminar permanentemente…",
        "Could not delete transcript": "No se pudo eliminar la transcripción",
        "Delete session permanently?": "¿Eliminar la sesión permanentemente?",
        "“{name}” and its transcript file will be permanently deleted. This cannot be undone.":
            "«{name}» y su archivo de transcripción se eliminarán permanentemente. "
            "Esto no se puede deshacer.",
        "Delete permanently": "Eliminar permanentemente",
        "New {name} session (advanced)…": "Nueva sesión de {name} (avanzada)…",
        "Continue last {name} session…": "Continuar la última sesión de {name}…",
        "New {name} session": "Nueva sesión de {name}",
        "Optional flags for this session.": "Opciones para esta sesión.",
        "Model": "Modelo",
        "Default": "Predeterminado",
        "Permission mode": "Modo de permisos",
        "Extra directory": "Directorio adicional",
        "Choose…": "Elegir…",
        "Choose a directory": "Elige un directorio",
        "Start": "Iniciar",
        "Save": "Guardar",
        "Set tab emoji": "Establecer emoji de pestaña",
        "Shown before the tab title. Leave empty to remove.":
            "Se muestra antes del título de la pestaña. Déjalo vacío para quitarlo.",
        "e.g. 🚀": "p. ej. 🚀",
        "OK": "Aceptar",
        "No MCP servers configured": "No hay servidores MCP configurados",
        "Global": "Global",
        "Available to every project": "Disponible para todos los proyectos",
        "MCP Servers": "Servidores MCP",
        "Read-only": "Solo lectura",
        "Reading transcript…": "Leyendo transcripción…",
        "Session details": "Detalles de la sesión",
        "Session ID": "ID de sesión",
        "Directory": "Directorio",
        "unknown": "desconocido",
        "Created": "Creada",
        "Last activity": "Última actividad",
        "Messages": "Mensajes",
        "Tool calls": "Llamadas a herramientas",
        "Models": "Modelos",
        "Tokens": "Tokens",
        "Transcript size": "Tamaño de la transcripción",
        "MCP": "MCP",
        "Available to this project": "Disponible para este proyecto",
        "Tools used in this session": "Herramientas usadas en esta sesión",
        "Recent activity": "Actividad reciente",
        "You": "Tú",
        "Claude": "Claude",
        "Follow system": "Seguir el sistema",
        "Light": "Claro",
        "Dark": "Oscuro",
        "Preferences": "Preferencias",
        "General": "General",
        "Terminal": "Terminal",
        "Font": "Fuente",
        "Applies to all terminal tabs": "Se aplica a todas las pestañas de terminal",
        "Reset to default font": "Restablecer la fuente predeterminada",
        "Scrollback lines": "Líneas de historial",
        "Easy copy & paste": "Copiado y pegado fáciles",
        "Ctrl+C copies selected text (otherwise interrupts as usual), Ctrl+V pastes, and right-click opens a copy/paste menu":
            "Ctrl+C copia el texto seleccionado (si no, interrumpe como de costumbre), Ctrl+V pega y el clic derecho abre un menú de copiar/pegar",
        "Copy": "Copiar",
        "Paste": "Pegar",
        "Select All": "Seleccionar todo",
        "Color theme": "Tema de color",
        "Appearance": "Apariencia",
        "Color scheme": "Esquema de color",
        "Language": "Idioma",
        "Restart to apply": "Reinicia para aplicar",
        "Notifications": "Notificaciones",
        "Notify when a session goes idle": "Notificar cuando una sesión quede inactiva",
        "Desktop notification when a background tab stops producing output":
            "Notificación de escritorio cuando una pestaña en segundo plano deja de producir salida",
        "Claude is waiting for your reply": "Claude está esperando tu respuesta",
        "Remove from favorites": "Quitar de favoritos",
        "Add to favorites": "Añadir a favoritos",
        "Sessions": "Sesiones",
        "Select sessions": "Seleccionar sesiones",
        "Show hidden sessions": "Mostrar sesiones ocultas",
        "MCP servers": "Servidores MCP",
        "About Agent Session Manager": "Acerca de Agent Session Manager",
        "Refresh session list": "Actualizar la lista de sesiones",
        "Search sessions…": "Buscar sesiones…",
        "Collapse all groups": "Contraer todos los grupos",
        "Expand all groups": "Expandir todos los grupos",
        "No sessions found": "No se encontraron sesiones",
        "{n} sessions": "{n} sesiones",
        "{n} projects": "{n} proyectos",
        "{n} open": "{n} abiertas",
        "Favorites": "Favoritos",
        "Open": "Abrir",
        "Open in Ghostty": "Abrir en Ghostty",
        "Fork session": "Bifurcar sesión",
        "Rename…": "Renombrar…",
        "Details…": "Detalles…",
        "Copy session ID": "Copiar ID de sesión",
        "Export as Markdown…": "Exportar como Markdown…",
        "Reveal transcript": "Mostrar transcripción",
        "Unhide session": "Mostrar sesión",
        "Hide session": "Ocultar sesión",
        "Move transcript to trash…": "Mover transcripción a la papelera…",
        "All": "Todas",
        "Select all (filtered) sessions": "Seleccionar todas las sesiones (filtradas)",
        "None": "Ninguna",
        "Clear selection": "Borrar selección",
        "Move selected transcripts to trash…":
            "Mover las transcripciones seleccionadas a la papelera…",
        "Hide selected": "Ocultar seleccionadas",
        "Remove selected from favorites": "Quitar seleccionadas de favoritos",
        "Add selected to favorites": "Añadir seleccionadas a favoritos",
        "Open selected in tabs": "Abrir seleccionadas en pestañas",
        "warning: project dir {cwd} no longer exists, starting in HOME":
            "advertencia: el directorio del proyecto {cwd} ya no existe, iniciando en HOME",
        "warning: `{cli}` not found in PATH — starting a plain shell":
            "advertencia: no se encontró `{cli}` en PATH — iniciando una shell simple",
        "failed to start shell: {msg}": "no se pudo iniciar la shell: {msg}",
        "Find in terminal…": "Buscar en la terminal…",
        "Previous match": "Coincidencia anterior",
        "Next match": "Coincidencia siguiente",
        "Set emoji…": "Establecer emoji…",
        "Close": "Cerrar",
        "Toggle sidebar (F9)": "Mostrar u ocultar la barra lateral (F9)",
        "New {name} session…": "Nueva sesión de {name}…",
        "New session (Ctrl+Shift+T)": "Nueva sesión (Ctrl+Mayús+T)",
        "Agent": "Agente",
        "Question": "Pregunta",
        "{n} questions": "{n} preguntas",
        "This prompt needs the terminal to answer.":
            "Esta petición debe responderse en la terminal.",
        "Answer in terminal": "Responder en la terminal",
        "New {name} chat…": "Nuevo chat de {name}…",
        "Chat with {name} — every file edit and command asks your permission first.":
            "Chat con {name}: cada edición de archivo y comando pide tu permiso primero.",
        "New {name} chat ({mode})": "Nuevo chat de {name} ({mode})",
        "ask, read-only": "preguntar, solo lectura",
        "trusted, auto-run": "de confianza, automático",
        "Read-only chat with {name} — analyses and answers, never edits.":
            "Chat de solo lectura con {name}: analiza y responde, nunca edita.",
        "Chat with {name} — ⚠ runs edits and commands automatically, without asking.":
            "Chat con {name}: ⚠ ejecuta ediciones y comandos automáticamente, sin preguntar.",
        "{name} wants to use {tool}": "{name} quiere usar {tool}",
        "Allow once": "Permitir una vez",
        "Always allow {tool}": "Permitir siempre {tool}",
        "Deny": "Denegar",
        "Allowed {tool}.": "{tool} permitido.",
        "Always allowing {tool}.": "Permitiendo siempre {tool}.",
        "Denied {tool}.": "{tool} denegado.",
        "Auto-allowed {tool}": "{tool} permitido automáticamente",
        "Ask {name}…": "Pregunta a {name}…",
        "Stop": "Detener",
        "{name} is thinking…": "{name} está pensando…",
        "Rate limited — try again later.": "Límite alcanzado — inténtalo más tarde.",
        "Error: {msg}": "Error: {msg}",
        "Session ended.": "Sesión finalizada.",
        "Replay…": "Reproducir…",
        "Replay — {name}": "Reproducción — {name}",
        "Previous": "Anterior",
        "Play": "Reproducir",
        "Next": "Siguiente",
        "Show all": "Mostrar todo",
        "Nothing to replay yet.": "Aún no hay nada que reproducir.",
        "Chat — {dir}": "Chat — {dir}",
        "Chat — {name}": "Chat — {name}",
        "Continue in chat": "Continuar en el chat",
        "Continue in chat ({mode})": "Continuar en el chat ({mode})",
        "Continuing the previous session — earlier messages aren't shown here.":
            "Continuando la sesión anterior: los mensajes anteriores no se muestran aquí.",
        "Close all tabs": "Cerrar todas las pestañas",
        "No session open": "Ninguna sesión abierta",
        "Pick a session from the sidebar, or start a new one.":
            "Elige una sesión en la barra lateral o inicia una nueva.",
        "Some transcripts could not be trashed":
            "No se pudieron enviar a la papelera algunas transcripciones",
        "Move {n} transcript(s) to trash?": "¿Mover {n} transcripción(es) a la papelera?",
        "The files are moved to the trash and can be restored.":
            "Los archivos se mueven a la papelera y se pueden restaurar.",
        "Move to Trash": "Mover a la papelera",
        "New window": "Nueva ventana",
        "You interrupted Claude here": "Interrumpiste a Claude aquí",
        "Restart now": "Reiniciar ahora",
        "Choose project directory": "Elegir directorio del proyecto",
        "Tab name": "Nombre de la pestaña",
        "Export session as Markdown": "Exportar sesión como Markdown",
        "Export failed": "Error al exportar",
        "Could not trash transcript": "No se pudo enviar la transcripción a la papelera",
        "Move transcript to trash?": "¿Mover la transcripción a la papelera?",
        "“{name}” will be removed from Claude's history.":
            "«{name}» se eliminará del historial de Claude.",
        "The file is moved to the trash and can be restored.":
            "El archivo se mueve a la papelera y se puede restaurar.",
    },
    "fr": {
        "Rename session": "Renommer la session",
        "Custom name": "Nom personnalisé",
        "Cancel": "Annuler",
        "Session list": "Liste des sessions",
        "Show folder path": "Afficher le chemin du dossier",
        "Show each session's project folder path in the sidebar":
            "Afficher le chemin du dossier de projet de chaque session dans la barre latérale",
        "Open session file…": "Ouvrir un fichier de session…",
        "Open session transcript": "Ouvrir une transcription de session",
        "Session transcripts (*.jsonl)": "Transcriptions de session (*.jsonl)",
        "Could not open transcript": "Impossible d'ouvrir la transcription",
        "The file couldn't be read as a session transcript.":
            "Le fichier n'a pas pu être lu comme une transcription de session.",
        "Delete permanently…": "Supprimer définitivement…",
        "Could not delete transcript": "Impossible de supprimer la transcription",
        "Delete session permanently?": "Supprimer définitivement la session ?",
        "“{name}” and its transcript file will be permanently deleted. This cannot be undone.":
            "« {name} » et son fichier de transcription seront définitivement supprimés. "
            "Cette action est irréversible.",
        "Delete permanently": "Supprimer définitivement",
        "New {name} session (advanced)…": "Nouvelle session {name} (avancé)…",
        "Continue last {name} session…": "Continuer la dernière session {name}…",
        "New {name} session": "Nouvelle session {name}",
        "Optional flags for this session.": "Options facultatives pour cette session.",
        "Model": "Modèle",
        "Default": "Par défaut",
        "Permission mode": "Mode d'autorisation",
        "Extra directory": "Répertoire supplémentaire",
        "Choose…": "Choisir…",
        "Choose a directory": "Choisir un répertoire",
        "Start": "Démarrer",
        "Save": "Enregistrer",
        "Set tab emoji": "Définir l’emoji de l’onglet",
        "Shown before the tab title. Leave empty to remove.":
            "Affiché avant le titre de l’onglet. Laisser vide pour le retirer.",
        "e.g. 🚀": "p. ex. 🚀",
        "OK": "OK",
        "No MCP servers configured": "Aucun serveur MCP configuré",
        "Global": "Global",
        "Available to every project": "Disponible pour tous les projets",
        "MCP Servers": "Serveurs MCP",
        "Read-only": "Lecture seule",
        "Reading transcript…": "Lecture de la transcription…",
        "Session details": "Détails de la session",
        "Session ID": "ID de session",
        "Directory": "Répertoire",
        "unknown": "inconnu",
        "Created": "Créée",
        "Last activity": "Dernière activité",
        "Messages": "Messages",
        "Tool calls": "Appels d’outils",
        "Models": "Modèles",
        "Tokens": "Jetons",
        "Transcript size": "Taille de la transcription",
        "MCP": "MCP",
        "Available to this project": "Disponible pour ce projet",
        "Tools used in this session": "Outils utilisés dans cette session",
        "Recent activity": "Activité récente",
        "You": "Vous",
        "Claude": "Claude",
        "Follow system": "Suivre le système",
        "Light": "Clair",
        "Dark": "Sombre",
        "Preferences": "Préférences",
        "General": "Général",
        "Terminal": "Terminal",
        "Font": "Police",
        "Applies to all terminal tabs": "S’applique à tous les onglets de terminal",
        "Reset to default font": "Réinitialiser la police par défaut",
        "Scrollback lines": "Lignes d’historique",
        "Easy copy & paste": "Copier-coller simplifié",
        "Ctrl+C copies selected text (otherwise interrupts as usual), Ctrl+V pastes, and right-click opens a copy/paste menu":
            "Ctrl+C copie le texte sélectionné (sinon interrompt comme d’habitude), Ctrl+V colle, et le clic droit ouvre un menu copier/coller",
        "Copy": "Copier",
        "Paste": "Coller",
        "Select All": "Tout sélectionner",
        "Color theme": "Thème de couleurs",
        "Appearance": "Apparence",
        "Color scheme": "Schéma de couleurs",
        "Language": "Langue",
        "Restart to apply": "Redémarrer pour appliquer",
        "Notifications": "Notifications",
        "Notify when a session goes idle": "Notifier lorsqu’une session devient inactive",
        "Desktop notification when a background tab stops producing output":
            "Notification de bureau lorsqu’un onglet en arrière-plan cesse de produire une sortie",
        "Claude is waiting for your reply": "Claude attend votre réponse",
        "Remove from favorites": "Retirer des favoris",
        "Add to favorites": "Ajouter aux favoris",
        "Sessions": "Sessions",
        "Select sessions": "Sélectionner des sessions",
        "Show hidden sessions": "Afficher les sessions masquées",
        "MCP servers": "Serveurs MCP",
        "About Agent Session Manager": "À propos d’Agent Session Manager",
        "Refresh session list": "Actualiser la liste des sessions",
        "Search sessions…": "Rechercher des sessions…",
        "Collapse all groups": "Réduire tous les groupes",
        "Expand all groups": "Développer tous les groupes",
        "No sessions found": "Aucune session trouvée",
        "{n} sessions": "{n} sessions",
        "{n} projects": "{n} projets",
        "{n} open": "{n} ouvertes",
        "Favorites": "Favoris",
        "Open": "Ouvrir",
        "Open in Ghostty": "Ouvrir dans Ghostty",
        "Fork session": "Bifurquer la session",
        "Rename…": "Renommer…",
        "Details…": "Détails…",
        "Copy session ID": "Copier l’ID de session",
        "Export as Markdown…": "Exporter en Markdown…",
        "Reveal transcript": "Afficher la transcription",
        "Unhide session": "Afficher la session",
        "Hide session": "Masquer la session",
        "Move transcript to trash…": "Mettre la transcription à la corbeille…",
        "All": "Tout",
        "Select all (filtered) sessions": "Sélectionner toutes les sessions (filtrées)",
        "None": "Aucune",
        "Clear selection": "Effacer la sélection",
        "Move selected transcripts to trash…":
            "Mettre les transcriptions sélectionnées à la corbeille…",
        "Hide selected": "Masquer la sélection",
        "Remove selected from favorites": "Retirer la sélection des favoris",
        "Add selected to favorites": "Ajouter la sélection aux favoris",
        "Open selected in tabs": "Ouvrir la sélection dans des onglets",
        "warning: project dir {cwd} no longer exists, starting in HOME":
            "avertissement : le répertoire de projet {cwd} n’existe plus, démarrage dans HOME",
        "warning: `{cli}` not found in PATH — starting a plain shell":
            "avertissement : `{cli}` introuvable dans le PATH — démarrage d’un shell simple",
        "failed to start shell: {msg}": "échec du démarrage du shell : {msg}",
        "Find in terminal…": "Rechercher dans le terminal…",
        "Previous match": "Correspondance précédente",
        "Next match": "Correspondance suivante",
        "Set emoji…": "Définir un emoji…",
        "Close": "Fermer",
        "Toggle sidebar (F9)": "Afficher/masquer la barre latérale (F9)",
        "New {name} session…": "Nouvelle session {name}…",
        "New session (Ctrl+Shift+T)": "Nouvelle session (Ctrl+Maj+T)",
        "Agent": "Agent",
        "Question": "Question",
        "{n} questions": "{n} questions",
        "This prompt needs the terminal to answer.":
            "Cette invite doit être traitée dans le terminal.",
        "Answer in terminal": "Répondre dans le terminal",
        "New {name} chat…": "Nouvelle discussion {name}…",
        "Chat with {name} — every file edit and command asks your permission first.":
            "Discussion avec {name} — chaque modification de fichier et commande "
            "demande d'abord votre permission.",
        "New {name} chat ({mode})": "Nouvelle discussion {name} ({mode})",
        "ask, read-only": "questions, lecture seule",
        "trusted, auto-run": "de confiance, automatique",
        "Read-only chat with {name} — analyses and answers, never edits.":
            "Discussion en lecture seule avec {name} — analyse et répond, ne modifie jamais.",
        "Chat with {name} — ⚠ runs edits and commands automatically, without asking.":
            "Discussion avec {name} — ⚠ exécute les modifications et commandes "
            "automatiquement, sans demander.",
        "{name} wants to use {tool}": "{name} veut utiliser {tool}",
        "Allow once": "Autoriser une fois",
        "Always allow {tool}": "Toujours autoriser {tool}",
        "Deny": "Refuser",
        "Allowed {tool}.": "{tool} autorisé.",
        "Always allowing {tool}.": "{tool} toujours autorisé désormais.",
        "Denied {tool}.": "{tool} refusé.",
        "Auto-allowed {tool}": "{tool} autorisé automatiquement",
        "Ask {name}…": "Demander à {name}…",
        "Stop": "Arrêter",
        "{name} is thinking…": "{name} réfléchit…",
        "Rate limited — try again later.": "Limite atteinte — réessayez plus tard.",
        "Error: {msg}": "Erreur : {msg}",
        "Session ended.": "Session terminée.",
        "Replay…": "Rejouer…",
        "Replay — {name}": "Relecture — {name}",
        "Previous": "Précédent",
        "Play": "Lecture",
        "Next": "Suivant",
        "Show all": "Tout afficher",
        "Nothing to replay yet.": "Rien à rejouer pour l’instant.",
        "Chat — {dir}": "Discussion — {dir}",
        "Chat — {name}": "Discussion — {name}",
        "Continue in chat": "Continuer dans la discussion",
        "Continue in chat ({mode})": "Continuer dans la discussion ({mode})",
        "Continuing the previous session — earlier messages aren't shown here.":
            "Reprise de la session précédente — les messages antérieurs ne sont pas affichés ici.",
        "Close all tabs": "Fermer tous les onglets",
        "No session open": "Aucune session ouverte",
        "Pick a session from the sidebar, or start a new one.":
            "Choisissez une session dans la barre latérale, ou démarrez-en une nouvelle.",
        "Some transcripts could not be trashed":
            "Certaines transcriptions n’ont pas pu être mises à la corbeille",
        "Move {n} transcript(s) to trash?": "Mettre {n} transcription(s) à la corbeille ?",
        "The files are moved to the trash and can be restored.":
            "Les fichiers sont mis à la corbeille et peuvent être restaurés.",
        "Move to Trash": "Mettre à la corbeille",
        "New window": "Nouvelle fenêtre",
        "You interrupted Claude here": "Vous avez interrompu Claude ici",
        "Restart now": "Redémarrer maintenant",
        "Choose project directory": "Choisir le répertoire du projet",
        "Tab name": "Nom de l’onglet",
        "Export session as Markdown": "Exporter la session en Markdown",
        "Export failed": "Échec de l’exportation",
        "Could not trash transcript": "Impossible de mettre la transcription à la corbeille",
        "Move transcript to trash?": "Mettre la transcription à la corbeille ?",
        "“{name}” will be removed from Claude's history.":
            "« {name} » sera retiré de l’historique de Claude.",
        "The file is moved to the trash and can be restored.":
            "Le fichier est mis à la corbeille et peut être restauré.",
    },
}

_HEADER = (
    'msgid ""\n'
    'msgstr ""\n'
    '"Project-Id-Version: claude-session-manager\\n"\n'
    '"Language: {lang}\\n"\n'
    '"MIME-Version: 1.0\\n"\n'
    '"Content-Type: text/plain; charset=UTF-8\\n"\n'
    '"Content-Transfer-Encoding: 8bit\\n"\n'
    '"Plural-Forms: nplurals=2; plural=(n != 1);\\n"\n\n'
)


def _escape(text: str) -> str:
    return text.replace("\\", "\\\\").replace('"', '\\"')


def main() -> None:
    for lang, entries in TRANSLATIONS.items():
        po_path = Path(__file__).resolve().parent / f"{lang}.po"
        body = [_HEADER.format(lang=lang)]
        for msgid, msgstr in entries.items():
            body.append(f'msgid "{_escape(msgid)}"\n')
            body.append(f'msgstr "{_escape(msgstr)}"\n\n')
        po_path.write_text("".join(body), encoding="utf-8")

        mo_dir = LOCALE / lang / "LC_MESSAGES"
        mo_dir.mkdir(parents=True, exist_ok=True)
        subprocess.run(
            ["msgfmt", "-o", str(mo_dir / f"{DOMAIN}.mo"), str(po_path)], check=True
        )
        print(f"{lang}: {len(entries)} strings → {po_path.name} + .mo")


if __name__ == "__main__":
    main()
