#!/usr/bin/env bash
# Install a "Collins (Debug + Pull)" launcher in the current user's app grid.
# Clicking it pulls this checkout, then starts the debug instance
# (COLLINS_APP_ID=com.episode6.Collins.Debug), so a stale build is never what
# you end up staring at.
#
# The checkout path is baked in from wherever this script lives, so the same
# command works on any machine regardless of where the repo was cloned.
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
APP_ID="com.episode6.Collins"
DEBUG_ID="$APP_ID.Debug"

BIN_DIR="$HOME/.local/bin"
APPS_DIR="$HOME/.local/share/applications"
ICON_DIR="$HOME/.local/share/icons/hicolor/scalable/apps"
LAUNCHER="$BIN_DIR/collins-debug-pull"
ENTRY="$APPS_DIR/$APP_ID.DebugPull.desktop"

mkdir -p "$BIN_DIR" "$APPS_DIR" "$ICON_DIR"

# The debug icon, so this entry stands on its own on a machine where
# data/install.sh was never run. Say which file is missing if the icons are
# ever renamed, rather than leaving a bare "cp: cannot stat" to interpret.
ICON_SRC="$REPO/data/icons/$DEBUG_ID.svg"
if [ ! -f "$ICON_SRC" ]; then
  echo "error: debug icon not found at $ICON_SRC" >&2
  echo "       (is $REPO a complete Collins checkout?)" >&2
  exit 1
fi
cp "$ICON_SRC" "$ICON_DIR/"

cat > "$LAUNCHER" <<EOF
#!/usr/bin/env bash
# Generated by $REPO/scripts/install-debug-launcher.sh — re-run it to update.
#
# No set -e on purpose: reaching the app is the point, so every step that can
# fail is handled explicitly below and nothing else gets to abort the launch.
set -u

REPO="$REPO"
LOG="\${XDG_CACHE_HOME:-\$HOME/.cache}/collins-debug-pull.log"

mkdir -p "\$(dirname "\$LOG")"
cd "\$REPO" || exit 1

# A failed pull (dirty tree, offline, nothing to fast-forward onto) must not
# block the launch — say so and start whatever is already checked out.
if ! { echo "=== \$(date -Is) git pull in \$REPO ==="; git pull --ff-only; } >"\$LOG" 2>&1; then
  notify-send -i $DEBUG_ID "Collins (Debug)" \\
    "git pull failed — starting the current checkout. See \$LOG" 2>/dev/null || true
fi

exec env COLLINS_APP_ID=$DEBUG_ID python3 -m collins
EOF
chmod +x "$LAUNCHER"

# A separate app id from the hidden $DEBUG_ID entry data/install.sh writes, so
# that installer never overwrites this one — but the same StartupWMClass, so
# the running window still lands on the debug icon in the dock.
cat > "$ENTRY" <<EOF
[Desktop Entry]
Type=Application
Name=Collins (Debug + Pull)
GenericName=Session Manager
Comment=Pull the latest source, then run the debug instance
Exec=$LAUNCHER
Path=$REPO
Icon=$DEBUG_ID
Terminal=false
Categories=Development;
Keywords=claude;ai;agent;terminal;session;code;collins;debug;
StartupNotify=true
StartupWMClass=$DEBUG_ID
EOF

update-desktop-database "$APPS_DIR" 2>/dev/null || true
gtk-update-icon-cache -t "$HOME/.local/share/icons/hicolor" 2>/dev/null || true

echo "Installed: $LAUNCHER"
echo "Installed: $ENTRY"
echo "Installed: $ICON_DIR/$DEBUG_ID.svg"
echo "Pulls and runs: $REPO"
