#!/usr/bin/env bash
# Install a "Collins (Debug + Pull)" launcher in the current user's app grid.
# Clicking it pulls this checkout, then starts the debug instance
# (COLLINS_APP_ID=com.episode6.Collins.Debug), so a stale build is never what
# you end up staring at. If the pull can't happen cleanly — the checkout is on
# some branch other than main, has uncommitted work, or git fails — it stops
# and says so rather than launching something other than the tip of main.
#
# The checkout path is baked in from wherever this script lives, so the same
# command works on any machine regardless of where the repo was cloned.
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
APP_ID="com.episode6.Collins"
DEBUG_ID="$APP_ID.Debug"

BIN_DIR="$HOME/.local/bin"
APPS_DIR="$HOME/.local/share/applications"
ICON_DIR="$HOME/.local/share/icons/hicolor/scalable/apps"
LAUNCHER="$BIN_DIR/collins-debug-pull"
ENTRY="$APPS_DIR/$APP_ID.DebugPull.desktop"

mkdir -p "$BIN_DIR" "$APPS_DIR" "$ICON_DIR"

# The debug icon, so this entry stands on its own on a machine where
# data/install.sh was never run. Say which file is missing if the icons are
# ever renamed, rather than leaving a bare "cp: cannot stat" to interpret.
ICON_SRC="$REPO/data/icons/$DEBUG_ID.svg"
if [ ! -f "$ICON_SRC" ]; then
  echo "error: debug icon not found at $ICON_SRC" >&2
  echo "       (is $REPO a complete Collins checkout?)" >&2
  exit 1
fi
cp "$ICON_SRC" "$ICON_DIR/"

cat > "$LAUNCHER" <<EOF
#!/usr/bin/env bash
# Generated by $REPO/scripts/install-debug-launcher.sh — re-run it to update.
#
# No set -e on purpose: every step that can fail is handled explicitly below,
# so the launch either runs the freshly pulled tip of main or doesn't happen
# at all. Anything else — a stale checkout, someone else's branch, a tree with
# uncommitted work in it — is not what "Debug + Pull" promises, so it bails
# with a notification instead of quietly starting the wrong thing.
set -u

REPO="$REPO"
LOG="\${XDG_CACHE_HOME:-\$HOME/.cache}/collins-debug-pull.log"

mkdir -p "\$(dirname "\$LOG")"

bail() {
  notify-send -u critical -i $DEBUG_ID "Collins (Debug) — not started" \\
    "\$1" 2>/dev/null || true
  echo "\$1" >&2
  exit 1
}

cd "\$REPO" || bail "\$REPO is gone — reinstall the launcher from a checkout."

# Every check below appends its own stderr here, so an unwritable log would
# fail them all and report the wrong reason. Say what actually went wrong.
echo "=== \$(date -Is) git pull in \$REPO ===" >"\$LOG" 2>/dev/null \\
  || bail "can't write the log at \$LOG"

BRANCH="\$(git symbolic-ref --quiet --short HEAD 2>>"\$LOG")" \\
  || bail "\$REPO has a detached HEAD, not main. See \$LOG"
[ "\$BRANCH" = main ] \\
  || bail "\$REPO is on '\$BRANCH', not main."

# --porcelain honours .gitignore, so build droppings don't count as dirty;
# staged, unstaged and untracked changes all do.
if [ -n "\$(git status --porcelain 2>>"\$LOG")" ]; then
  bail "\$REPO has uncommitted changes — commit or stash them first."
fi

git pull --ff-only >>"\$LOG" 2>&1 \\
  || bail "git pull failed in \$REPO. See \$LOG"

exec env COLLINS_APP_ID=$DEBUG_ID python3 -m collins
EOF
chmod +x "$LAUNCHER"

# A separate app id from the hidden $DEBUG_ID entry data/install.sh writes, so
# that installer never overwrites this one — but the same StartupWMClass, so
# the running window still lands on the debug icon in the dock.
cat > "$ENTRY" <<EOF
[Desktop Entry]
Type=Application
Name=Collins (Debug + Pull)
GenericName=Session Manager
Comment=Pull the latest main, then run the debug instance
Exec=$LAUNCHER
Path=$REPO
Icon=$DEBUG_ID
Terminal=false
Categories=Development;
Keywords=claude;ai;agent;terminal;session;code;collins;debug;
StartupNotify=true
StartupWMClass=$DEBUG_ID
EOF

update-desktop-database "$APPS_DIR" 2>/dev/null || true
gtk-update-icon-cache -t "$HOME/.local/share/icons/hicolor" 2>/dev/null || true

echo "Installed: $LAUNCHER"
echo "Installed: $ENTRY"
echo "Installed: $ICON_DIR/$DEBUG_ID.svg"
echo "Pulls and runs: $REPO"
